182 feature qrcode new
nlom0218/teacher_browser pull request #186
Opened 2022-08-24 12:31 UTC by soave424

2022-08-24 12:37 UTC, nlom0218 commented on src/Components/Qrcode/QrcodeInput.js
> +  };
Url 컴포넌트 밖을 클릭해도 qr코드가 만들어지는거죠?

2022-08-24 12:38 UTC, nlom0218 commented on src/Components/Qrcode/Qrcontext.js
> +        <div>{pick === true ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}</div>
해당 부분을 좀 더 간단하게 나타낼 수 있습니다!

2022-08-24 12:44 UTC, soave424 commented on src/Components/Qrcode/Qrcontext.js
> +      {" "}
확인!

2022-08-24 12:45 UTC, soave424 commented on src/Components/Qrcode/QrcodeInput.js
> +  };
삭제

2022-08-25 08:18 UTC, soave424 commented on src/Components/Qrcode/QrPrint/QrPrintMain.js
> +  };
콜백함수가 잘 구현이 안 되는데 useEffect와 같은 역할을 하나요??

2022-08-25 08:30 UTC, soave424 commented on src/Components/Qrcode/Qrcontext.js
> +        <div>{pick === true ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}</div>
수정 했는데 맞나요??

2022-08-25 08:31 UTC, soave424 commented on src/Components/Qrcode/Qrcontext.js
> +        <div>{pick === true ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}</div>
push 했는데 commit 에서 새로운 거 올라와 있는데 여기는 안 바뀐 것 같은데 바뀌었나요???

2022-08-25 08:32 UTC, soave424 commented
입력값이 잘 전달이 안 되는데 그 부분 한 번 봐주세요!!

2022-08-25 09:25 UTC, nlom0218 commented on src/Components/Qrcode/QrPrint/QrPrintMain.js
> +  };
setState(prev => ....)
이런식으로 콜백함수를 사용할 수 있습니다. prev는 해당 state의 이전 값을 나타내요. 여기서는 num값이 되겠네요.

2022-08-25 09:27 UTC, nlom0218 commented on src/Components/Qrcode/Qrcontext.js
> +        <div>{pick === true ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}</div>
div태그는 필요할 수도 있어요. 하지만 `pick`이라는 변수 자체가 ture, false를 나타내기 때문에 굳이 `pick === "true"`로 하지 않고 단지 `pick`만 사용하여 `pick`에 따라 어떤 컴포넌트가 렌더링 되는지 정할 수 있습니다.

2022-08-25 09:28 UTC, nlom0218 commented
어디 부분의 입력값이 전달이 안되는건가요?

2022-08-25 09:31 UTC, nlom0218 commented on src/Components/Qrcode/QrPrint/QrPrintMain.js
> +  //   }
위의 코드는 클래스형 컴포넌트를 다룰 때 사용합니다. 함수형 컴포넌트에서는 사용하지 않아요.

2022-08-25 09:39 UTC, nlom0218 commented on package.json
> +    "qrcode": "^1.5.1",
저는 해당 라이브러리보다 https://www.npmjs.com/package/qrcode.react 요게 더 사용하기 간편해 보여요!

2022-08-27 00:35 UTC, soave424 commented
1. 새 창으로 데이터 보내는 방법이 잘 안 됨.
2. 보관함에 "url 주소:" 글씨 유/무
3. 인쇄창 구성 / 이름 저장값 넘기기 -> 데이터 저장 타이밍 
4. DB (qr이름, url주소, 큐알코드 이미지)
5. 디자인 요청(캐릭터, 메뉴아이콘)

2022-08-27 02:23 UTC, nlom0218 commented
```javascript
  const timerUrl =
    process.env.NODE_ENV === "production"
      ? `https://teachercan.com/timer_popup/countup`
      : `http://localhost:3000/timer_popup/countup`;
  const windowFeatures = "left=100,top=100,width=1600,height=800, popup";

  const onClickNewWindow = () => {
    window.open(timerUrl, "timer", windowFeatures);
  };
```

위의 방법이 새로운 탭을 여는 방법입니다.(타이머창과 같습니다.)
그리고 데이터를 넘겨야 할 땐 로컬스토리지에 저장을 해야 하지 않을까 합니다.

2022-08-27 02:30 UTC, nlom0218 commented on src/Components/Qrcode/Qrresult.js
> +  };
이렇게 정보를 전달할 수 있나 보네요? 처음보는 방법입니다!

2022-08-27 02:36 UTC, nlom0218 commented on src/Components/Qrcode/Qrresult.js
> +  };
위의 방법에서 데이터가 잘 넘어가지 않나봐요? 좀더 찾아보고 안되면 로컬스토리지를 이용해봐야겠습니다.
https://developer.mozilla.org/ko/docs/Web/API/Window/postMessage
작성하신 방법과 다르게 사용되는 거 같아요!

```javascript
const popup = window.open("url")
popup.postMessage("msg", targetOrigin, object")
```

저도 한 번도 사용하지 않았던 메서드라 확인은 해봐야할듯하네요

2022-08-27 02:36 UTC, nlom0218 commented
> 1. 새 창으로 데이터 보내는 방법이 잘 안 됨.
> 2. 보관함에 "url 주소:" 글씨 유/무
> 3. 인쇄창 구성 / 이름 저장값 넘기기 -> 데이터 저장 타이밍
> 4. DB (qr이름, url주소, 큐알코드 이미지)
> 5. 디자인 요청(캐릭터, 메뉴아이콘)

2~4는 내일 회의 때 이야기 해봐요!

2022-08-27 02:39 UTC, nlom0218 commented on src/Components/Qrcode/Qrcontext.js
> +        <div>{pick === true ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}</div>
"=== true"를 삭제할 수 있습니다. `pick`자체가 true, false를 나타내기 때문이죠
```jsx
<div>{pick  ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}</div>
```

2022-08-27 02:45 UTC, nlom0218 requested changes

2022-08-27 02:45 UTC, nlom0218 commented on src/Components/Qrcode/Qrcontext.js
> +      {pick === true ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}
```jsx
{pick ? <RiCheckboxLine /> : <RiCheckboxBlankLine />}
```

2022-09-01 13:32 UTC, nlom0218 commented
백앤드 qr코드 자료
https://github.com/teacher-kiwi/teacher-browser-back/blob/dev/server/src/typeDefs-resolvers/qrcode/qrcode.graphql
https://github.com/teacher-kiwi/teacher-browser-back/blob/dev/server/src/typeDefs-resolvers/qrcode/qrcode.js

2022-09-11 07:31 UTC, nlom0218 commented on src/Components/Qrcode/Qroptionbtn.js
> +    refetchQueries: [{ query: QRCODES_QUERY, variables: { userEmail, qrcodeId } }, { query: ME_QUERY }],
큐알코드의 내용을 refetchQueries를 통해 불러오게 됩니다. 단, variables는 useEmail만 필요하기 때문에 qrcodeId는 삭제해야 합니다. 또한 ME_QUERY도 다시 불러오지 않아도 되므로 삭제해야 합니다.(만약 필요하다면 그대로 두고요)

2022-09-11 07:31 UTC, nlom0218 commented on src/Components/Qrcode/Qroptionbtn.js
> +  };
삭제 뮤테이션은 잘 작성하신 듯 해요. 다만 데이터가 잘 들어오는지 콘솔로 한 번 확인해주세요.
그리고 여려개 삭제를 하기 위해선 반복문을 통해 삭제 뮤테이션을 실행하거나 백앤드에서 새로운 뮤테이션을 만들어야 해요. 일단
배열에 삭제할 큐알코드 아이디를 요소로 넣고 forEach 메서드를 통해 구현해보시겠어요?

2022-09-12 00:45 UTC, soave424 commented on src/Components/Qrcode/Qroptionbtn.js
> +    refetchQueries: [{ query: QRCODES_QUERY, variables: { userEmail, qrcodeId } }, { query: ME_QUERY }],
네! ME_QUERY랑 qrcodeId 삭제했습니다.

2022-09-12 00:56 UTC, soave424 commented on src/Components/Qrcode/Qroptionbtn.js
> +  };
map 대신 forEach 메서드를 이용하는 이유가 있을까요??? 삭제 뮤테이션이 실행이 안 되네요ㅠ

2022-09-12 01:44 UTC, nlom0218 commented on src/Components/Qrcode/Qroptionbtn.js
> +  };
map 메서드는 배열 내의 모든 요소 각각에 대하여 주어진 함수를 호출한 결과를 모아 새로운 배열을 반환하는 메서드이고 forEach 메서드는 반복문을 통해 자신을 호출한 배열을 순회하면서 수행해야 할 처리를 콜백 함수로 전달받아 반복 호출하는 메서드입니다.

단순 반복을 위해서라면 forEach를 사용하여 새로운 배열을 만들겠다 라면 map를 사용하시면 되요

2022-09-12 04:04 UTC, nlom0218 commented on src/Components/Qrcode/Qrcontext.js
> +  const [addPickQr, setAddPickQr] = useState([]);
해당 state는 부모 컨테이너인 QrcodeStorage.js에서 선언해서 자식 컨테이너에 전달해야 합니다.
그래야 state를 Qroptionsbtn.js에서 사용하실 수 있어요. 

삭제할 목록이 추가가 아니라 대체되는 이유도 위와 같은 이유 때문이라고 생각이 되요.

2022-09-12 04:04 UTC, nlom0218 commented on src/Components/Qrcode/Qroptionbtn.js
> +      variables: { userEmail },
delqrcode 뮤테이션을 실행하기 위해선 qrcodeId 변수가 필요한데 그것을 넣지 않아 오류가 뜹니다.

2022-09-12 05:22 UTC, soave424 commented on src/Components/Qrcode/Qrcontext.js
> +  const [addPickQr, setAddPickQr] = useState([]);
네!! 해결했습니다!

2022-09-12 05:33 UTC, nlom0218 commented
어떤 오류가 나오나요?

2022-09-12 07:26 UTC, soave424 commented
index.ts:63 Uncaught (in promise) Error: Response not successful: Received status code 400
    at new ApolloError (index.ts:63:1)
    at Object.error (QueryManager.ts:314:1)
    at notifySubscription (module.js:136:1)
    at onNotify (module.js:174:1)
    at SubscriptionObserver.error (module.js:228:1)
    at Object.error (asyncMap.ts:48:1)
    at notifySubscription (module.js:136:1)
    at onNotify (module.js:174:1)
    at SubscriptionObserver.error (module.js:228:1)
    at iteration.ts:13:1

2022-09-12 07:31 UTC, nlom0218 commented
>

2022-09-12 07:34 UTC, nlom0218 commented on src/Components/Qrcode/Qroptionbtn.js
> +    refetchQueries: [{ query: QRCODES_QUERY, variables: { userEmail, qrcodeId } }],
QRCODES_QUERY는 qrcodeId가 필요없습니다! 삭제 해주셔야 해요!

2022-09-12 07:34 UTC, nlom0218 commented on src/Components/Qrcode/Qroptionbtn.js
> +  const qrcodeId = qrcodeIdList[0];
아마 여기서 qrocdeId가 불러오지 않을 듯 한데... 데이터가 잘 불러와지나요?
로컬스토리지에 저장해서 컴포넌트가 리랜더링이 안될거 같아요. 부모 컴포넌트에서 스테이트를 만들어서 자식 컴포넌트에 
props롤 전달해봐요!

콘솔로도 데이터가 잘 들어왔는지 확인해주세요!

2022-09-13 11:15 UTC, soave424 commented on src/Components/Qrcode/Qroptionbtn.js
> +  const qrcodeId = qrcodeIdList[0];
데이터는 잘 들어가서 콘솔에는 qrcodeid가 뜨는데 그걸 qrcodeID로 넣기만 하면 오류가 떠요ㅠ

2022-09-14 11:06 UTC, nlom0218 approved these changes

2022-09-14 11:06 UTC, merged